=== JosipPufler/Java2-Everdell/xml/dtd/gameActions.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT GameActions (GameAction+)>

<!ELEMENT GameAction ((CardPlayed|Location|Season), PlayerState)>
<!ATTLIST GameAction player-number CDATA #REQUIRED>
<!ATTLIST GameAction game-action-type CDATA #REQUIRED>
<!ATTLIST GameAction time CDATA #REQUIRED>

<!ELEMENT CardPlayed (#PCDATA)>
<!ELEMENT Season (#PCDATA)>
<!ELEMENT Location (Name, X, Y)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT X (#PCDATA)>
<!ELEMENT Y (#PCDATA)>

<!ELEMENT PlayerState (FreeWorkers, ResourceGroup, CardsInHand, CardsInPlay, BoardResources)>

<!ELEMENT FreeWorkers (#PCDATA)>

<!ELEMENT ResourceGroup (Berries, Resin, Pebbles, Twigs, Points)>
<!ELEMENT Berries (#PCDATA)>
<!ELEMENT Resin (#PCDATA)>
<!ELEMENT Pebbles (#PCDATA)>
<!ELEMENT Twigs (#PCDATA)>
<!ELEMENT Points (#PCDATA)>

<!ELEMENT BoardResources (BoardBerries, BoardResin, BoardPebbles, BoardTwigs, DeckSize)>
<!ELEMENT BoardBerries (#PCDATA)>
<!ELEMENT BoardResin (#PCDATA)>
<!ELEMENT BoardPebbles (#PCDATA)>
<!ELEMENT BoardTwigs (#PCDATA)>
<!ELEMENT DeckSize (#PCDATA)>

<!ELEMENT CardsInHand (CardInHand*)>
<!ELEMENT CardsInPlay (CardInPlay*)>
<!ELEMENT CardInHand (#PCDATA)>
<!ELEMENT CardInPlay (#PCDATA)>

=== JosipPufler/Java2-Everdell/xml/gameActions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE GameActions SYSTEM "dtd/gameActions.dtd">
<GameActions>
    <GameAction game-action-type="PLACE_WORKER" player-number="ONE" time="2025-02-13T20:03:49.488786200">
        <Location>
            <Name>location_3T</Name>
            <X>168.8</X>
            <Y>312.0</Y>
        </Location>
        <PlayerState>
            <FreeWorkers>1</FreeWorkers>
            <ResourceGroup>
                <Berries>0</Berries>
                <Resin>0</Resin>
                <Pebbles>0</Pebbles>
                <Twigs>3</Twigs>
                <Points>0</Points>
            </ResourceGroup>
            <CardsInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.GeneralStore</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.Inn</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.ClockTower</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.FairGrounds</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.University</CardInHand>
            </CardsInHand>
            <CardsInPlay/>
            <BoardResources>
                <BoardBerries>30</BoardBerries>
                <BoardResin>25</BoardResin>
                <BoardPebbles>20</BoardPebbles>
                <BoardTwigs>27</BoardTwigs>
                <DeckSize>95</DeckSize>
            </BoardResources>
        </PlayerState>
    </GameAction>
    <GameAction game-action-type="PLACE_WORKER" player-number="TWO" time="2025-02-13T20:03:50.212228">
        <Location>
            <Name>location_2R</Name>
            <X>349.6</X>
            <Y>335.2</Y>
        </Location>
        <PlayerState>
            <FreeWorkers>1</FreeWorkers>
            <ResourceGroup>
                <Berries>0</Berries>
                <Resin>2</Resin>
                <Pebbles>0</Pebbles>
                <Twigs>0</Twigs>
                <Points>0</Points>
            </ResourceGroup>
            <CardsInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.PostalPigeon</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Historian</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Bard</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Queen</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.TwigBarge</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.Monastery</CardInHand>
            </CardsInHand>
            <CardsInPlay/>
            <BoardResources>
                <BoardBerries>30</BoardBerries>
                <BoardResin>23</BoardResin>
                <BoardPebbles>20</BoardPebbles>
                <BoardTwigs>27</BoardTwigs>
                <DeckSize>95</DeckSize>
            </BoardResources>
        </PlayerState>
    </GameAction>
    <GameAction game-action-type="PLACE_WORKER" player-number="ONE" time="2025-02-13T20:03:51.399274500">
        <Location>
            <Name>location_2C1Pt</Name>
            <X>485.6</X>
            <Y>336.0</Y>
        </Location>
        <PlayerState>
            <FreeWorkers>0</FreeWorkers>
            <ResourceGroup>
                <Berries>0</Berries>
                <Resin>0</Resin>
                <Pebbles>0</Pebbles>
                <Twigs>3</Twigs>
                <Points>1</Points>
            </ResourceGroup>
            <CardsInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.GeneralStore</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.Inn</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.ClockTower</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.FairGrounds</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.University</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.Dungeon</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.Crane</CardInHand>
            </CardsInHand>
            <CardsInPlay/>
            <BoardResources>
                <BoardBerries>30</BoardBerries>
                <BoardResin>23</BoardResin>
                <BoardPebbles>20</BoardPebbles>
                <BoardTwigs>27</BoardTwigs>
                <DeckSize>93</DeckSize>
            </BoardResources>
        </PlayerState>
    </GameAction>
    <GameAction game-action-type="PLACE_WORKER" player-number="TWO" time="2025-02-13T20:03:52.379779900">
        <Location>
            <Name>location_1B</Name>
            <X>753.6</X>
            <Y>316.8</Y>
        </Location>
        <PlayerState>
            <FreeWorkers>0</FreeWorkers>
            <ResourceGroup>
                <Berries>1</Berries>
                <Resin>2</Resin>
                <Pebbles>0</Pebbles>
                <Twigs>0</Twigs>
                <Points>0</Points>
            </ResourceGroup>
            <CardsInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.PostalPigeon</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Historian</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Bard</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Queen</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.TwigBarge</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.Monastery</CardInHand>
            </CardsInHand>
            <CardsInPlay/>
            <BoardResources>
                <BoardBerries>29</BoardBerries>
                <BoardResin>23</BoardResin>
                <BoardPebbles>20</BoardPebbles>
                <BoardTwigs>27</BoardTwigs>
                <DeckSize>93</DeckSize>
            </BoardResources>
        </PlayerState>
    </GameAction>
    <GameAction game-action-type="PREPARE_FOR_SEASON" player-number="ONE" time="2025-02-13T20:04:17.231191">
        <Season>SPRING</Season>
        <PlayerState>
            <FreeWorkers>2</FreeWorkers>
            <ResourceGroup>
                <Berries>1</Berries>
                <Resin>2</Resin>
                <Pebbles>0</Pebbles>
                <Twigs>0</Twigs>
                <Points>1</Points>
            </ResourceGroup>
            <CardsInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.PostalPigeon</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Historian</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Bard</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Queen</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.TwigBarge</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.Monastery</CardInHand>
            </CardsInHand>
            <CardsInPlay/>
            <BoardResources>
                <BoardBerries>29</BoardBerries>
                <BoardResin>23</BoardResin>
                <BoardPebbles>20</BoardPebbles>
                <BoardTwigs>27</BoardTwigs>
                <DeckSize>93</DeckSize>
            </BoardResources>
        </PlayerState>
    </GameAction>
    <GameAction game-action-type="PREPARE_FOR_SEASON" player-number="TWO" time="2025-02-13T20:04:19.068039">
        <Season>SPRING</Season>
        <PlayerState>
            <FreeWorkers>2</FreeWorkers>
            <ResourceGroup>
                <Berries>1</Berries>
                <Resin>2</Resin>
                <Pebbles>0</Pebbles>
                <Twigs>0</Twigs>
                <Points>0</Points>
            </ResourceGroup>
            <CardsInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.PostalPigeon</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Historian</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Bard</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Queen</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.TwigBarge</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.Monastery</CardInHand>
            </CardsInHand>
            <CardsInPlay/>
            <BoardResources>
                <BoardBerries>29</BoardBerries>
                <BoardResin>23</BoardResin>
                <BoardPebbles>20</BoardPebbles>
                <BoardTwigs>27</BoardTwigs>
                <DeckSize>93</DeckSize>
            </BoardResources>
        </PlayerState>
    </GameAction>
    <GameAction game-action-type="PLACE_WORKER" player-number="ONE" time="2025-02-13T20:04:22.758937">
        <Location>
            <Name>location_2R</Name>
            <X>340.8</X>
            <Y>328.0</Y>
        </Location>
        <PlayerState>
            <FreeWorkers>1</FreeWorkers>
            <ResourceGroup>
                <Berries>1</Berries>
                <Resin>4</Resin>
                <Pebbles>0</Pebbles>
                <Twigs>0</Twigs>
                <Points>1</Points>
            </ResourceGroup>
            <CardsInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.PostalPigeon</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Historian</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Bard</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.critters.Queen</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.TwigBarge</CardInHand>
                <CardInHand>hr.algebra.everdell.models.cards.constructs.Monastery</CardInHand>
